// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllerp

import (
	"github.com/arfanxn/coursefan-gofiber/app/http/controllers"
	"github.com/arfanxn/coursefan-gofiber/app/policies"
	"github.com/arfanxn/coursefan-gofiber/app/repositories"
	"github.com/arfanxn/coursefan-gofiber/app/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitAuthController(db *gorm.DB) *controllers.AuthController {
	userRepository := repositories.NewUserRepository(db)
	mediaRepository := repositories.NewMediaRepository(db)
	tokenRepository := repositories.NewTokenRepository(db)
	authService := services.NewAuthService(userRepository, mediaRepository, tokenRepository)
	authController := controllers.NewAuthController(authService)
	return authController
}

func InitCourseController(db *gorm.DB) *controllers.CourseController {
	courseRepository := repositories.NewCourseRepository(db)
	curRepository := repositories.NewCourseUserRoleRepository(db)
	courseService := services.NewCourseService(courseRepository)
	coursePolicy := policies.NewCoursePolicy(curRepository)
	courseController := controllers.NewCourseController(coursePolicy, courseService)
	return courseController
}


func InitLecturePartController(db *gorm.DB) *controllers.LecturePartController {
	lecturePartRepository := repositories.NewLecturePartRepository(db)
	curRepository := repositories.NewCourseUserRoleRepository(db)
	lecturePartService := services.NewLecturePartService(lecturePartRepository)
	lecturePartPolicy := policies.NewLecturePartPolicy(lecturePartRepository,curRepository)
	lecturePartController := controllers.NewLecturePartController(lecturePartPolicy, lecturePartService)
	return lecturePartController
}
