// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package seederp

import (
	"github.com/arfanxn/coursefan-gofiber/app/repositories"
	"github.com/arfanxn/coursefan-gofiber/database/seeders"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitUserSeeder(db *gorm.DB) *seeders.UserSeeder {
	userRepository := repositories.NewUserRepository(db)
	userSeeder := seeders.NewUserSeeder(userRepository)
	return userSeeder
}
